SELECT 
  PROFILE_ID,
  CUSTOMER_NAME_EN,
  INVOICE_DATE,
  INVOICE_NO,
  EXECID,
  STOCK_ID,
  QUNTY,
  SECOND_PROFILE
FROM back_office.CMP_EMP_TBL_DAILY_ORDERS
WHERE INVOICE_DATE = :close_date
  AND FLAG = 1
ORDER BY INVOICE_DATE
