-- Placeholder: Replace with actual operations view/query from DBA
-- Bind variable :close_date = YYYYMMDD string
SELECT A.PROFILE_ID "رقم العميل الداخلي",CUSTOMER_NAME_AR "اسم العميل",C.NIN "الكود الموحد",case when A.OPERATION_ID = 13 then 'Buy' else 'Sell' end "الأمر",E.STOCK_CODE "كود الورقة"
, QNTY "الكمية المتبقية",rtrim(ltrim(to_char(A.PRICE,'9990.999')))   "السعر", EDATA_CAST_DATETIME(SUBSTR(INIT_TIMESTAMP,0,8),'D,/,M,/,Y') "تاريخ الأمر",
EDATA_CAST_DATETIME ( A.EXPIRATION_DATE , 'D,/,M,/,Y')  "تاريخ انتهاء الأمر",A.EXECUTED_QNTY "الكمية المنفذة",F.CUSTODIAN_DESC_EN"أمين الحفظ",
G.DESC_AR as "حاله الأمر"
FROM T_TRNX_DAILY A INNER JOIN T_PROFILE_INFO_SETTING B ON A.PROFILE_ID=B.PROFILE_ID
INNER JOIN T_INVESTMENT_ACCOUNT_PROFILE C ON B.PROFILE_ID=C.PROFILE_ID AND C.MARKET_ID=1
INNER JOIN T_PORTFOLIOS D ON A.PROFILE_ID=D.PROFILE_ID AND A.PORTFOLIO_ID=D.PORTFOLIO_ID 
INNER JOIN T_STOCK E ON A.STOCK_ID = E.STOCK_ID
INNER JOIN BO_CUSTODIAN F ON A.CUSTODIAN_ID=F.CUSTODIAN_ID
INNER JOIN T_TRNX_STATUS g ON G.TRNX_STATUS_ID = A.TRNX_STATUS_ID
WHERE D.IB_ID = 138 and a.OPERATION_ID in (13,14) and a.TRNX_STATUS_ID in (98,180,102)
