-- ============================================================
-- CMP_CLIENTS_TBL_CTRL_DOB — Trigger signal table.
-- One row inserted per scheduler run (1st of every month).
-- Owner: BACK_OFFICE
-- Synonym: CMP_CLIENTS_TBL_CTRL_DOB (see db/00_setup/02_create_synonyms.sql)
-- ============================================================

CREATE TABLE CMP_CLIENTS_TBL_CTRL_DOB 
(
  MONTHLY_DATE NUMBER
);

-- Grants to PUBLIC
GRANT FLASHBACK         ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO PUBLIC;
GRANT DEBUG             ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO PUBLIC;
GRANT QUERY REWRITE     ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO PUBLIC;
GRANT ON COMMIT REFRESH ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO PUBLIC;
GRANT REFERENCES        ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO PUBLIC;
GRANT UPDATE            ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO PUBLIC;
GRANT SELECT            ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO PUBLIC;
GRANT INSERT            ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO PUBLIC;
GRANT INDEX             ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO PUBLIC;
GRANT DELETE            ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO PUBLIC;
GRANT ALTER             ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO PUBLIC;

-- Grants to EDATA_PL
GRANT FLASHBACK         ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO EDATA_PL;
GRANT DEBUG             ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO EDATA_PL;
GRANT QUERY REWRITE     ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO EDATA_PL;
GRANT ON COMMIT REFRESH ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO EDATA_PL;
GRANT REFERENCES        ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO EDATA_PL;
GRANT UPDATE            ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO EDATA_PL;
GRANT SELECT            ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO EDATA_PL;
GRANT INSERT            ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO EDATA_PL;
GRANT INDEX             ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO EDATA_PL;
GRANT DELETE            ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO EDATA_PL;
GRANT ALTER             ON BACK_OFFICE.CMP_CLIENTS_TBL_CTRL_DOB TO EDATA_PL;
