CREATE TABLE WORKER_MAIL_RECIPIENTS 
(
  RECIPIENT_ID NUMBER NOT NULL 
, RULE_ID NUMBER NOT NULL 
, RECIP_TYPE VARCHAR2(3 BYTE) NOT NULL 
, ADDRESS VARCHAR2(320 BYTE) NOT NULL 
, ADDRESS_KIND VARCHAR2(10 BYTE) DEFAULT 'EMAIL' 
, IS_ACTIVE CHAR(1 BYTE) DEFAULT 'Y' 
, CONSTRAINT SYS_C001583552 PRIMARY KEY 
  (
    RECIPIENT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C001583552 ON WORKER_MAIL_RECIPIENTS (RECIPIENT_ID ASC) 
      LOGGING 
      TABLESPACE BACK_OFFICE_TS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BACK_OFFICE_TS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE INDEX IX_WMRC_RULE ON WORKER_MAIL_RECIPIENTS (RULE_ID ASC, RECIP_TYPE ASC, IS_ACTIVE ASC) 
LOGGING 
TABLESPACE BACK_OFFICE_TS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE WORKER_MAIL_RECIPIENTS
ADD CONSTRAINT SYS_C001583549 CHECK 
(RECIP_TYPE IN ('TO','CC','BCC'))
ENABLE;

ALTER TABLE WORKER_MAIL_RECIPIENTS
ADD CONSTRAINT SYS_C001583550 CHECK 
(ADDRESS_KIND IN ('EMAIL','GROUP'))
ENABLE;

ALTER TABLE WORKER_MAIL_RECIPIENTS
ADD CONSTRAINT SYS_C001583551 CHECK 
(IS_ACTIVE IN ('Y','N'))
ENABLE;
