CREATE TABLE WORKER_MAIL_RULE_TARGET 
(
  TARGET_ID NUMBER NOT NULL 
, RULE_ID NUMBER NOT NULL 
, RECIP_TYPE VARCHAR2(3 BYTE) NOT NULL 
, TARGET_KIND VARCHAR2(10 BYTE) NOT NULL 
, ADDRESS_ID NUMBER 
, GROUP_ID NUMBER 
, IS_ACTIVE CHAR(1 BYTE) DEFAULT 'Y' NOT NULL 
, CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL 
, UPDATED_AT TIMESTAMP(6) 
, CONSTRAINT PK_WORKER_MAIL_RULE_TARGET PRIMARY KEY 
  (
    TARGET_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_WORKER_MAIL_RULE_TARGET ON WORKER_MAIL_RULE_TARGET (TARGET_ID ASC) 
      LOGGING 
      TABLESPACE BACK_OFFICE_TS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BACK_OFFICE_TS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

ALTER TABLE WORKER_MAIL_RULE_TARGET
ADD CONSTRAINT UX_WMRT_NO_DUP UNIQUE 
(
  RULE_ID 
, RECIP_TYPE 
, TARGET_KIND 
, ADDRESS_ID 
, GROUP_ID 
)
USING INDEX 
(
    CREATE UNIQUE INDEX UX_WMRT_NO_DUP ON WORKER_MAIL_RULE_TARGET (RULE_ID ASC, RECIP_TYPE ASC, TARGET_KIND ASC, ADDRESS_ID ASC, GROUP_ID ASC) 
    LOGGING 
    TABLESPACE BACK_OFFICE_TS 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 1048576 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

ALTER TABLE WORKER_MAIL_RULE_TARGET
ADD CONSTRAINT FK_WMRT_ADDRESS FOREIGN KEY
(
  ADDRESS_ID 
)
REFERENCES WORKER_MAIL_ADDRESS
(
  ADDRESS_ID 
)
ENABLE;

ALTER TABLE WORKER_MAIL_RULE_TARGET
ADD CONSTRAINT FK_WMRT_GROUP FOREIGN KEY
(
  GROUP_ID 
)
REFERENCES WORKER_MAIL_GROUP
(
  GROUP_ID 
)
ENABLE;

ALTER TABLE WORKER_MAIL_RULE_TARGET
ADD CONSTRAINT FK_WMRT_RULE FOREIGN KEY
(
  RULE_ID 
)
REFERENCES WORKER_MAIL_RULES
(
  RULE_ID 
)
ENABLE;

ALTER TABLE WORKER_MAIL_RULE_TARGET
ADD CONSTRAINT CK_WMRT_ACTIVE CHECK 
(IS_ACTIVE IN ('Y','N'))
ENABLE;

ALTER TABLE WORKER_MAIL_RULE_TARGET
ADD CONSTRAINT CK_WMRT_ONE_TARGET CHECK 
((TARGET_KIND = 'EMAIL' AND ADDRESS_ID IS NOT NULL AND GROUP_ID IS NULL)
 OR (TARGET_KIND = 'GROUP' AND GROUP_ID   IS NOT NULL AND ADDRESS_ID IS NULL))
ENABLE;

ALTER TABLE WORKER_MAIL_RULE_TARGET
ADD CONSTRAINT CK_WMRT_RECIP_TYPE CHECK 
(RECIP_TYPE IN ('TO','CC','BCC'))
ENABLE;

ALTER TABLE WORKER_MAIL_RULE_TARGET
ADD CONSTRAINT CK_WMRT_TARGET_KIND CHECK 
(TARGET_KIND IN ('EMAIL','GROUP'))
ENABLE;
