CREATE TABLE WORKER_MAIL_SIGNATURE_REGISTRY 
(
  SIGNATURE_KEY VARCHAR2(100 BYTE) NOT NULL 
, LANGUAGE_CODE VARCHAR2(2 BYTE) NOT NULL 
, SIGNATURE_FILE VARCHAR2(400 BYTE) NOT NULL 
, IS_ACTIVE CHAR(1 BYTE) DEFAULT 'Y' NOT NULL 
, CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL 
, UPDATED_AT TIMESTAMP(6) 
) 
LOGGING 
TABLESPACE BACK_OFFICE_TS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

ALTER TABLE WORKER_MAIL_SIGNATURE_REGISTRY
ADD CONSTRAINT CK_WMSR_ACT CHECK 
(IS_ACTIVE IN ('Y','N'))
ENABLE;

ALTER TABLE WORKER_MAIL_SIGNATURE_REGISTRY
ADD CONSTRAINT CK_WMSR_LANG CHECK 
(LANGUAGE_CODE IN ('AR','EN'))
ENABLE;
