CREATE TABLE WORKER_MAIL_TEMPLATE_REGISTRY 
(
  TEMPLATE_KEY VARCHAR2(100 BYTE) NOT NULL 
, LANGUAGE_CODE VARCHAR2(2 BYTE) NOT NULL 
, DIRECTION VARCHAR2(3 BYTE) DEFAULT 'LTR' NOT NULL 
, SUBJECT_TPL VARCHAR2(500 BYTE) 
, BODY_FILE VARCHAR2(400 BYTE) NOT NULL 
, IS_ACTIVE CHAR(1 BYTE) DEFAULT 'Y' NOT NULL 
, CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL 
, UPDATED_AT TIMESTAMP(6) 
) 
LOGGING 
TABLESPACE BACK_OFFICE_TS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

ALTER TABLE WORKER_MAIL_TEMPLATE_REGISTRY
ADD CONSTRAINT CK_WMTR_ACT CHECK 
(IS_ACTIVE IN ('Y','N'))
ENABLE;

ALTER TABLE WORKER_MAIL_TEMPLATE_REGISTRY
ADD CONSTRAINT CK_WMTR_DIR CHECK 
(DIRECTION IN ('LTR','RTL'))
ENABLE;

ALTER TABLE WORKER_MAIL_TEMPLATE_REGISTRY
ADD CONSTRAINT CK_WMTR_LANG CHECK 
(LANGUAGE_CODE IN ('AR','EN'))
ENABLE;
