CREATE TABLE WORKER_MAIL_RULES 
(
  RULE_ID NUMBER NOT NULL 
, DOMAIN VARCHAR2(50 BYTE) NOT NULL 
, REPORT_CODE VARCHAR2(100 BYTE) 
, EVENT_TYPE VARCHAR2(20 BYTE) NOT NULL 
, IS_ACTIVE CHAR(1 BYTE) DEFAULT 'Y' 
, NOTIFY_ENABLED CHAR(1 BYTE) DEFAULT 'Y' 
, SUBJECT_SUFFIX VARCHAR2(100 BYTE) 
, TEMPLATE_KEY VARCHAR2(100 BYTE) 
, SIGNATURE_KEY VARCHAR2(100 BYTE) 
, FROM_ADDRESS VARCHAR2(200 BYTE) 
, CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP 
, UPDATED_AT TIMESTAMP(6) 
, LANGUAGE_CODE VARCHAR2(2 BYTE) DEFAULT 'EN' NOT NULL 
, CONSTRAINT SYS_C001583559 PRIMARY KEY 
  (
    RULE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C001583559 ON WORKER_MAIL_RULES (RULE_ID ASC) 
      LOGGING 
      TABLESPACE BACK_OFFICE_TS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BACK_OFFICE_TS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE INDEX IX_WMR_DOMAIN_EVENT ON WORKER_MAIL_RULES (DOMAIN ASC, EVENT_TYPE ASC, IS_ACTIVE ASC) 
LOGGING 
TABLESPACE BACK_OFFICE_TS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX IX_WMR_DOMAIN_REPORT_EVENT ON WORKER_MAIL_RULES (DOMAIN ASC, REPORT_CODE ASC, EVENT_TYPE ASC, IS_ACTIVE ASC) 
LOGGING 
TABLESPACE BACK_OFFICE_TS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX UX_WMR_UNIQ_RULE ON WORKER_MAIL_RULES (DOMAIN ASC, NVL("REPORT_CODE",'__DOMAIN__') ASC, EVENT_TYPE ASC, LANGUAGE_CODE ASC) 
LOGGING 
TABLESPACE BACK_OFFICE_TS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE WORKER_MAIL_RULES
ADD CONSTRAINT CK_WMR_LANG CHECK 
(LANGUAGE_CODE IN ('AR','EN'))
ENABLE;

ALTER TABLE WORKER_MAIL_RULES
ADD CONSTRAINT SYS_C001583556 CHECK 
(IS_ACTIVE IN ('Y','N'))
ENABLE;

ALTER TABLE WORKER_MAIL_RULES
ADD CONSTRAINT SYS_C001583557 CHECK 
(NOTIFY_ENABLED IN ('Y','N'))
ENABLE;
