CREATE TABLE WORKER_EXECUTION 
(
  CLOSE_DATE VARCHAR2(8 BYTE) 
, STATUS VARCHAR2(20 BYTE) NOT NULL 
, STARTED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP 
, FINISHED_AT TIMESTAMP(6) 
, UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP 
, ERROR_CODE VARCHAR2(50 BYTE) 
, ERROR_MSG VARCHAR2(2000 BYTE) 
, DETAILS CLOB 
, TRIGGER_TYPE VARCHAR2(50 BYTE) DEFAULT 'day-close' 
) 
LOGGING 
TABLESPACE BACK_OFFICE_TS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL 
LOB (DETAILS) STORE AS SYS_LOB0002386911C00008$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE BACK_OFFICE_TS 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);
