CREATE TABLE WORKER_REPORT_LOG 
(
  ID NUMBER 
, CLOSE_DATE VARCHAR2(8 BYTE) NOT NULL 
, REPORT_ID VARCHAR2(50 BYTE) NOT NULL 
, DOMAIN VARCHAR2(50 BYTE) NOT NULL 
, STATUS VARCHAR2(20 BYTE) NOT NULL 
, ROW_COUNT NUMBER 
, FILE_PATH VARCHAR2(500 BYTE) 
, ERROR_CODE VARCHAR2(50 BYTE) 
, ERROR_MSG VARCHAR2(2000 BYTE) 
, RETRYABLE CHAR(1 BYTE) DEFAULT 'N' 
, ATTEMPT_NO NUMBER DEFAULT 1 
, STARTED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP 
, FINISHED_AT TIMESTAMP(6) 
, TRIGGER_TYPE VARCHAR2(50 BYTE) DEFAULT 'day-close' 
) 
LOGGING 
TABLESPACE BACK_OFFICE_TS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE INDEX IDX_REPORT_LOG_RETRY ON WORKER_REPORT_LOG (CLOSE_DATE ASC, STATUS ASC, RETRYABLE ASC) 
LOGGING 
TABLESPACE BACK_OFFICE_TS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
