CREATE TABLE WORKER_MAIL_GROUP 
(
  GROUP_ID NUMBER NOT NULL 
, GROUP_CODE VARCHAR2(100 BYTE) NOT NULL 
, GROUP_NAME VARCHAR2(200 BYTE) 
, IS_ACTIVE CHAR(1 BYTE) DEFAULT 'Y' NOT NULL 
, CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL 
, UPDATED_AT TIMESTAMP(6) 
, CONSTRAINT PK_WORKER_MAIL_GROUP PRIMARY KEY 
  (
    GROUP_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_WORKER_MAIL_GROUP ON WORKER_MAIL_GROUP (GROUP_ID ASC) 
      LOGGING 
      TABLESPACE BACK_OFFICE_TS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BACK_OFFICE_TS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;
