CREATE TABLE WORKER_MAIL_ADDRESS 
(
  ADDRESS_ID NUMBER NOT NULL 
, ADDRESS VARCHAR2(320 BYTE) NOT NULL 
, DISPLAY_NAME VARCHAR2(200 BYTE) 
, IS_ACTIVE CHAR(1 BYTE) DEFAULT 'Y' NOT NULL 
, CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL 
, UPDATED_AT TIMESTAMP(6) 
, CONSTRAINT PK_WORKER_MAIL_ADDRESS PRIMARY KEY 
  (
    ADDRESS_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_WORKER_MAIL_ADDRESS ON WORKER_MAIL_ADDRESS (ADDRESS_ID ASC) 
      LOGGING 
      TABLESPACE BACK_OFFICE_TS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BACK_OFFICE_TS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE UNIQUE INDEX UX_WORKER_MAIL_ADDRESS_LOWER ON WORKER_MAIL_ADDRESS (LOWER("ADDRESS") ASC) 
LOGGING 
TABLESPACE BACK_OFFICE_TS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE WORKER_MAIL_ADDRESS
ADD CONSTRAINT CK_WORKER_MAIL_ADDRESS_ACTIVE CHECK 
(IS_ACTIVE IN ('Y','N'))
ENABLE;
